### ISSUE TITLE
Approach for newer versions of android

### ISSUE THREAD

**Issue by hwaqar44** [maryamhashemi/WiFiDirect#1]
We have implemented the same  logic but it seems it doesn't work for newer versions of andoids. LIke andoir 8.0 or 9.0 . Does it work in your case. Have you check?

**Comment by maryamhashemi** [comment]
For Android version above 6, you need to add location permission to manifest file and be sure the user granted this permission, so I've added the checkLocationPermission() method that asks the user for location permission. you can see the code in this commit (https://github.com/maryamhashemi/WiFiDirect/commit/d7de94df5493a1eb36a9cdc42a84813bd8d761e6).

Hope this works for you.
